### ISSUE TITLE
Exception on Android

### ISSUE THREAD

**Issue by dpyeates** [Gaspard-Bruno/react-native-static-safe-area-insets#17]
I am getting the following exception on Android in my application:

``
2020-04-18 15:58:30.280 18532-18720/com.app E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
        at com.gaspardbruno.staticsafeareainsets.RNStaticSafeAreaInsetsModule.getSafeAreaInsets(RNStaticSafeAreaInsetsModule.java:65)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
``

**Comment by yigithanyucedag** [comment]
Same error here on Android

**Comment by Macrow** [comment]
same error

**Comment by mpereira96** [comment]
Hello, we have a PR ready to address this issue: https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/pull/19
There should be a new version with this fix soon.

**Comment by dpyeates** [comment]
Any update on when we can expect the new version with the fix for this please?

**Comment by Plitzer** [comment]
Could this please be looked at ASAP? This completely breaks android builds and the previous version has unusable insets for android

**Comment by jpamarohorta** [comment]
Sorry for the delay. The PR was just merged and released in [2.1.1](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.1.1).
