### ISSUE TITLE
Exception in HostObject::get: for prop 'RNStaticSafeAreaInsets'

### ISSUE THREAD

**Issue by dansiemens** [Gaspard-Bruno/react-native-static-safe-area-insets#20]
I've had a few crash reports come through crashlytics, but it's really not obvious to me what's happening here. Any help would be appreciated. Device info for latest crash included.

Version: 2.1.1

**Device**
Brand: samsung
Model: Galaxy A20
Orientation: Portrait
RAM free: 654.35 MB
Disk free: 3.04 GB 

**Operating System**
 Version: 10
Orientation: Portrait
Rooted: No 

```
Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get: for prop 'RNStaticSafeAreaInsets': <unknown exception>, js engine: hermes, stack:
v@1:86634
d@1:86327
o@1:85953
anonymous@1:1029868
v@1:86634
d@1:86327
o@1:85953
anonymous@1:1029042
v@1:86634
d@1:86327
o@1:85953
anonymous@1:1026417
v@1:86634
d@1:86327
o@1:85953
anonymous@1:703318
v@1:86634
d@1:86284
o@1:85953
anonymous@1:93171
R@1:467611
run@1:467897
runApplication@1:468406
value@1:118225
anonymous@1:116755
value@1:117822
value@1:116713

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by robzyb** [comment]
I am getting a huge cluster of crash reports on Crashlytics with the same error, however my hotspot is happening for Samsung S10e phones.

#17 claims to fix this, but I am running off the latest master branch and continue to see this error coming through.

```
Fatal Exception: com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get: for prop 'RNStaticSafeAreaInsets': <unknown exception>, js engine: hermes, stack:
v@1:28672
d@1:28365
o@1:27991
anonymous@1:622348
v@1:28672
d@1:28365
o@1:27991
anonymous@1:495496
v@1:28672
d@1:28365
o@1:27991
anonymous@1:35092
v@1:28672
d@1:28322
o@1:27991
global@1:27723

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by robzyb** [comment]
@dansiemens, are you using [react-native-splash-screen](https://github.com/crazycodeboy/react-native-splash-screen) or anything else that might confuse react-native-static-safe-area-insets when the [app loads](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/blob/master/android/src/main/java/com/gaspardbruno/staticsafeareainsets/RNStaticSafeAreaInsetsModule.java#L38)?

**Comment by dansiemens** [comment]
@robzyb yes, using react-native-splash-screen `3.2.0`

**Comment by cmcleese** [comment]
Is there some kind of incompatibility with [react-native-splash-screen ](https://github.com/crazycodeboy/react-native-splash-screen) ?

I'm using rn-splash-screens.
I'm getting some crash logs as:
```
Fatal Exception: com.facebook.react.common.c
Error: Exception in HostObject::get(propName:RNStaticSafeAreaInsets): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetTop()' on a null object reference, stack: 
```

I'm using `"react-native-static-safe-area-insets": "1.3.4"`.
Does the latest version v2.1.1 which includes [#17](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/issues/17) fix this?

**Comment by omaryoussef** [comment]
Is there any update on this issue? I'm still seeing this happening on Samsung Galaxy S20 and OnePlus 7 Pro.

**Comment by medonagy45** [comment]
I am getting the same issue

**Comment by jpamarohorta** [comment]
Hello, thank your for the fallback @medonagy45 it was integrated into release [2.2.0](https://github.com/Gaspard-Bruno/react-native-static-safe-area-insets/releases/tag/v2.2.0), it should be fixed now.
